### ISSUE TITLE
Just a bug I'm facing!

### ISSUE THREAD

**Issue by rollins1338** [Seconb/RivalsX#1]
Hey, just wanted to share this issue. Any idea what could be wrong?

I have python 3.13 installed, ran the install_libraries.bat as admin (installed everything) but when I run the Runcolorbot.bat as admin it just shows a CMD for One second and just closes.
I tried both driver and LGHUB.
I'm on borderless as well in-game.
I ran the .py file to see what was wrong and this is what I got.
![0aaaa120](https://github.com/user-attachments/assets/bfe5cc0a-4d35-4afe-bf48-2e2b41dbeacc)

**Comment by rollins1338** [comment]
Fixed it! Just use python 3.9

**Comment by minhnhatCoder** [comment]
Did it work, can you show some of gameplay
